name: Build Backend Subtree

permissions:
  contents: write

on:
  push:
    branches:
      - master
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  split-backend:
    name: Split backend subtree
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create backend subtree branch
        run: |
          git branch -D deploy-backend 2>/dev/null || true
          git subtree split --prefix=backend -b deploy-backend

      - name: Push backend subtree branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin deploy-backend --force
