name: Build and Deploy Frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_SERVER_URL: ${{ secrets.REACT_APP_API_SERVER_URL }}
      REACT_APP_WEBSOCKET_SERVER_URL: ${{ secrets.REACT_APP_WEBSOCKET_SERVER_URL }}

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.5.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Add .htaccess to build output
        run: |
          cat <<'EOF' > build/.htaccess
          RewriteEngine On
          RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
          EOF

      - name: Upload build to Cloudways via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT || '22' }}
          local_path: ./frontend/build/
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
          sftp_only: true
          delete: true
